source "https://rubygems.org"

gem "lita"

# Uncomment to use the HipChat adapter
# gem "lita-hipchat"
gem "redis"
gem "lita-slack"
gem "lita-google-images"
gem "lita-catfacts"
gem "lita-ermahgerd"
gem "lita-excuses"
gem 'lita-eval', '~> 0.1.0'
gem 'lita-faker', '~> 0.1.0'
gem "lita-karma"
# Uncomment to use the IRC adapter
# gem "lita-irc"

# Add handlers to give Lita new functionality.
# For example:
# gem "lita-google-images"
# gem "lita-karma"
